enum ResponseTerms {
    PAGE_NOT_FOUND = "PAGE_NOT_FOUND",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    REQUEST_SUCCESSFUL = "REQUEST_SUCCESSFUL",
    RESOURCE_CREATED = "RESOURCE_CREATED",
    NO_CONTENT = "NO_CONTENT",
    BAD_REQUEST = "BAD_REQUEST",
    UNAUTHORIZED = "UNAUTHORIZED",
    FORBIDDEN = "FORBIDDEN",
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED",
    BAD_GATEWAY = "BAD_GATEWAY",
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
    UNKNOWN_ERROR = "UNKNOWN_ERROR",
  }

  export default ResponseTerms;
  