enum AppTerms {
  ERROR = "ERROR",
  SUCCESS = "SUCCESS",
  FAILED = "FAILED",
  TO_MANY_REQUESTS_FROM_THIS_IP_TRY_AGAIN_AFTER_HOUR = "TO_MANY_REQUESTS_FROM_THIS_IP_TRY_AGAIN_AFTER_HOUR",
}


export default AppTerms;